# Generated by Django 2.1 on 2022-09-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='Image_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.AddField(
            model_name='product',
            name='Name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
